select * from Estados

insert into Estados values('Aguascalientes', 'AGS')
insert into Estados values('Baja California Nte', 'BCN')
insert into Estados values('Baja California Sur', 'BCS')
insert into Estados values('Campeche', 'CAMP')
insert into Estados values('Coahuila', 'COAH')
insert into Estados values('Colima', 'COL')
insert into Estados values('Chiapas', 'CHIS')
insert into Estados values('Chihuahua', 'CHIH')
insert into Estados values('Distrito Federal', 'DF')
insert into Estados values('Durango', 'DGO')
insert into Estados values('Guanjuato', 'GTO')
insert into Estados values('Guerrero', 'GRO')
insert into Estados values('Hidalgo', 'HGO')
insert into Estados values('Jalisco', 'JAL')
insert into Estados values('Estado de Mexico', 'MEX')
insert into Estados values('Michoacan', 'MICH')
insert into Estados values('Morelos', 'MOR')
insert into Estados values('Nayarit', 'NAY')
insert into Estados values('Nuevo Leon', 'NL')
insert into Estados values('Oaxaca', 'OAX')
insert into Estados values('Puebla', 'PUE')
insert into Estados values('Queretaro', 'QRO')
insert into Estados values('Quintana Roo', 'QROO')
insert into Estados values('San Luis Potosi', 'SLP')
insert into Estados values('Sinaloa', 'SIN')
insert into Estados values('Sonora', 'SON')
insert into Estados values('Tabasco', 'TAB')
insert into Estados values('Tamaulipas', 'TAMP')
insert into Estados values('Tlaxcala', 'TLAX')
insert into Estados values('Veracruz', 'VER')
insert into Estados values('Yucatan', 'YUC')
insert into Estados values('Zacatecas', 'ZAC')
insert into Estados values('Ciudad de Mexico', 'CDMX')


