//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProAgro.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProagroEntities : DbContext
    {
        public ProagroEntities()
            : base("name=ProagroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Georeferencias> Georeferencias { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
